//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalWebClient.HospitalService1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="getAllApp", Namespace="http://schemas.datacontract.org/2004/07/HospitalService1")]
    [System.SerializableAttribute()]
    public partial class getAllApp : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataTable allAppField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataTable allApp {
            get {
                return this.allAppField;
            }
            set {
                if ((object.ReferenceEquals(this.allAppField, value) != true)) {
                    this.allAppField = value;
                    this.RaisePropertyChanged("allApp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="getAllDoctors", Namespace="http://schemas.datacontract.org/2004/07/HospitalService1")]
    [System.SerializableAttribute()]
    public partial class getAllDoctors : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataTable allDoctorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataTable allDoctor {
            get {
                return this.allDoctorField;
            }
            set {
                if ((object.ReferenceEquals(this.allDoctorField, value) != true)) {
                    this.allDoctorField = value;
                    this.RaisePropertyChanged("allDoctor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Doctor", Namespace="http://schemas.datacontract.org/2004/07/HospitalService1")]
    [System.SerializableAttribute()]
    public partial class Doctor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string d_addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string d_contactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string d_emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string d_experienceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string d_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string d_specialityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string d_address {
            get {
                return this.d_addressField;
            }
            set {
                if ((object.ReferenceEquals(this.d_addressField, value) != true)) {
                    this.d_addressField = value;
                    this.RaisePropertyChanged("d_address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string d_contact {
            get {
                return this.d_contactField;
            }
            set {
                if ((object.ReferenceEquals(this.d_contactField, value) != true)) {
                    this.d_contactField = value;
                    this.RaisePropertyChanged("d_contact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string d_email {
            get {
                return this.d_emailField;
            }
            set {
                if ((object.ReferenceEquals(this.d_emailField, value) != true)) {
                    this.d_emailField = value;
                    this.RaisePropertyChanged("d_email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string d_experience {
            get {
                return this.d_experienceField;
            }
            set {
                if ((object.ReferenceEquals(this.d_experienceField, value) != true)) {
                    this.d_experienceField = value;
                    this.RaisePropertyChanged("d_experience");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string d_name {
            get {
                return this.d_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.d_nameField, value) != true)) {
                    this.d_nameField = value;
                    this.RaisePropertyChanged("d_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string d_speciality {
            get {
                return this.d_specialityField;
            }
            set {
                if ((object.ReferenceEquals(this.d_specialityField, value) != true)) {
                    this.d_specialityField = value;
                    this.RaisePropertyChanged("d_speciality");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="deleteDoctor", Namespace="http://schemas.datacontract.org/2004/07/HospitalService1")]
    [System.SerializableAttribute()]
    public partial class deleteDoctor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int d_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int d_id {
            get {
                return this.d_idField;
            }
            set {
                if ((this.d_idField.Equals(value) != true)) {
                    this.d_idField = value;
                    this.RaisePropertyChanged("d_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Patient", Namespace="http://schemas.datacontract.org/2004/07/HospitalService1")]
    [System.SerializableAttribute()]
    public partial class Patient : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string p_contactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string p_emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string p_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string p_passwd1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string p_passwd2Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string p_contact {
            get {
                return this.p_contactField;
            }
            set {
                if ((object.ReferenceEquals(this.p_contactField, value) != true)) {
                    this.p_contactField = value;
                    this.RaisePropertyChanged("p_contact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string p_email {
            get {
                return this.p_emailField;
            }
            set {
                if ((object.ReferenceEquals(this.p_emailField, value) != true)) {
                    this.p_emailField = value;
                    this.RaisePropertyChanged("p_email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string p_name {
            get {
                return this.p_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.p_nameField, value) != true)) {
                    this.p_nameField = value;
                    this.RaisePropertyChanged("p_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string p_passwd1 {
            get {
                return this.p_passwd1Field;
            }
            set {
                if ((object.ReferenceEquals(this.p_passwd1Field, value) != true)) {
                    this.p_passwd1Field = value;
                    this.RaisePropertyChanged("p_passwd1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string p_passwd2 {
            get {
                return this.p_passwd2Field;
            }
            set {
                if ((object.ReferenceEquals(this.p_passwd2Field, value) != true)) {
                    this.p_passwd2Field = value;
                    this.RaisePropertyChanged("p_passwd2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookApp", Namespace="http://schemas.datacontract.org/2004/07/HospitalService1")]
    [System.SerializableAttribute()]
    public partial class BookApp : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string a_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string a_descField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ad_emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ap_emailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string a_date {
            get {
                return this.a_dateField;
            }
            set {
                if ((object.ReferenceEquals(this.a_dateField, value) != true)) {
                    this.a_dateField = value;
                    this.RaisePropertyChanged("a_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string a_desc {
            get {
                return this.a_descField;
            }
            set {
                if ((object.ReferenceEquals(this.a_descField, value) != true)) {
                    this.a_descField = value;
                    this.RaisePropertyChanged("a_desc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ad_email {
            get {
                return this.ad_emailField;
            }
            set {
                if ((object.ReferenceEquals(this.ad_emailField, value) != true)) {
                    this.ad_emailField = value;
                    this.RaisePropertyChanged("ad_email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ap_email {
            get {
                return this.ap_emailField;
            }
            set {
                if ((object.ReferenceEquals(this.ap_emailField, value) != true)) {
                    this.ap_emailField = value;
                    this.RaisePropertyChanged("ap_email");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HospitalService1.IHospitalService1")]
    public interface IHospitalService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService1/getallapp", ReplyAction="http://tempuri.org/IHospitalService1/getallappResponse")]
        HospitalWebClient.HospitalService1.getAllApp getallapp(string pid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService1/getallapp", ReplyAction="http://tempuri.org/IHospitalService1/getallappResponse")]
        System.Threading.Tasks.Task<HospitalWebClient.HospitalService1.getAllApp> getallappAsync(string pid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService1/getDoctors", ReplyAction="http://tempuri.org/IHospitalService1/getDoctorsResponse")]
        HospitalWebClient.HospitalService1.getAllDoctors getDoctors();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService1/getDoctors", ReplyAction="http://tempuri.org/IHospitalService1/getDoctorsResponse")]
        System.Threading.Tasks.Task<HospitalWebClient.HospitalService1.getAllDoctors> getDoctorsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService1/insertDoctor", ReplyAction="http://tempuri.org/IHospitalService1/insertDoctorResponse")]
        string insertDoctor(HospitalWebClient.HospitalService1.Doctor doctor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService1/insertDoctor", ReplyAction="http://tempuri.org/IHospitalService1/insertDoctorResponse")]
        System.Threading.Tasks.Task<string> insertDoctorAsync(HospitalWebClient.HospitalService1.Doctor doctor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService1/updateDoctor", ReplyAction="http://tempuri.org/IHospitalService1/updateDoctorResponse")]
        string updateDoctor(HospitalWebClient.HospitalService1.Doctor doctor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService1/updateDoctor", ReplyAction="http://tempuri.org/IHospitalService1/updateDoctorResponse")]
        System.Threading.Tasks.Task<string> updateDoctorAsync(HospitalWebClient.HospitalService1.Doctor doctor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService1/deleteDoctor", ReplyAction="http://tempuri.org/IHospitalService1/deleteDoctorResponse")]
        string deleteDoctor(HospitalWebClient.HospitalService1.deleteDoctor dd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService1/deleteDoctor", ReplyAction="http://tempuri.org/IHospitalService1/deleteDoctorResponse")]
        System.Threading.Tasks.Task<string> deleteDoctorAsync(HospitalWebClient.HospitalService1.deleteDoctor dd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService1/validCredential", ReplyAction="http://tempuri.org/IHospitalService1/validCredentialResponse")]
        string validCredential(string uname, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService1/validCredential", ReplyAction="http://tempuri.org/IHospitalService1/validCredentialResponse")]
        System.Threading.Tasks.Task<string> validCredentialAsync(string uname, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService1/ptvalidCredential", ReplyAction="http://tempuri.org/IHospitalService1/ptvalidCredentialResponse")]
        string ptvalidCredential(string useremail, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService1/ptvalidCredential", ReplyAction="http://tempuri.org/IHospitalService1/ptvalidCredentialResponse")]
        System.Threading.Tasks.Task<string> ptvalidCredentialAsync(string useremail, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService1/insertPatient", ReplyAction="http://tempuri.org/IHospitalService1/insertPatientResponse")]
        string insertPatient(HospitalWebClient.HospitalService1.Patient patient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService1/insertPatient", ReplyAction="http://tempuri.org/IHospitalService1/insertPatientResponse")]
        System.Threading.Tasks.Task<string> insertPatientAsync(HospitalWebClient.HospitalService1.Patient patient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService1/updatePatient", ReplyAction="http://tempuri.org/IHospitalService1/updatePatientResponse")]
        string updatePatient(HospitalWebClient.HospitalService1.Patient patient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService1/updatePatient", ReplyAction="http://tempuri.org/IHospitalService1/updatePatientResponse")]
        System.Threading.Tasks.Task<string> updatePatientAsync(HospitalWebClient.HospitalService1.Patient patient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService1/logout", ReplyAction="http://tempuri.org/IHospitalService1/logoutResponse")]
        void logout();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService1/logout", ReplyAction="http://tempuri.org/IHospitalService1/logoutResponse")]
        System.Threading.Tasks.Task logoutAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService1/bookAppointment", ReplyAction="http://tempuri.org/IHospitalService1/bookAppointmentResponse")]
        string bookAppointment(HospitalWebClient.HospitalService1.BookApp bapp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService1/bookAppointment", ReplyAction="http://tempuri.org/IHospitalService1/bookAppointmentResponse")]
        System.Threading.Tasks.Task<string> bookAppointmentAsync(HospitalWebClient.HospitalService1.BookApp bapp);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHospitalService1Channel : HospitalWebClient.HospitalService1.IHospitalService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HospitalService1Client : System.ServiceModel.ClientBase<HospitalWebClient.HospitalService1.IHospitalService1>, HospitalWebClient.HospitalService1.IHospitalService1 {
        
        public HospitalService1Client() {
        }
        
        public HospitalService1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HospitalService1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HospitalService1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HospitalService1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HospitalWebClient.HospitalService1.getAllApp getallapp(string pid) {
            return base.Channel.getallapp(pid);
        }
        
        public System.Threading.Tasks.Task<HospitalWebClient.HospitalService1.getAllApp> getallappAsync(string pid) {
            return base.Channel.getallappAsync(pid);
        }
        
        public HospitalWebClient.HospitalService1.getAllDoctors getDoctors() {
            return base.Channel.getDoctors();
        }
        
        public System.Threading.Tasks.Task<HospitalWebClient.HospitalService1.getAllDoctors> getDoctorsAsync() {
            return base.Channel.getDoctorsAsync();
        }
        
        public string insertDoctor(HospitalWebClient.HospitalService1.Doctor doctor) {
            return base.Channel.insertDoctor(doctor);
        }
        
        public System.Threading.Tasks.Task<string> insertDoctorAsync(HospitalWebClient.HospitalService1.Doctor doctor) {
            return base.Channel.insertDoctorAsync(doctor);
        }
        
        public string updateDoctor(HospitalWebClient.HospitalService1.Doctor doctor) {
            return base.Channel.updateDoctor(doctor);
        }
        
        public System.Threading.Tasks.Task<string> updateDoctorAsync(HospitalWebClient.HospitalService1.Doctor doctor) {
            return base.Channel.updateDoctorAsync(doctor);
        }
        
        public string deleteDoctor(HospitalWebClient.HospitalService1.deleteDoctor dd) {
            return base.Channel.deleteDoctor(dd);
        }
        
        public System.Threading.Tasks.Task<string> deleteDoctorAsync(HospitalWebClient.HospitalService1.deleteDoctor dd) {
            return base.Channel.deleteDoctorAsync(dd);
        }
        
        public string validCredential(string uname, string password) {
            return base.Channel.validCredential(uname, password);
        }
        
        public System.Threading.Tasks.Task<string> validCredentialAsync(string uname, string password) {
            return base.Channel.validCredentialAsync(uname, password);
        }
        
        public string ptvalidCredential(string useremail, string password) {
            return base.Channel.ptvalidCredential(useremail, password);
        }
        
        public System.Threading.Tasks.Task<string> ptvalidCredentialAsync(string useremail, string password) {
            return base.Channel.ptvalidCredentialAsync(useremail, password);
        }
        
        public string insertPatient(HospitalWebClient.HospitalService1.Patient patient) {
            return base.Channel.insertPatient(patient);
        }
        
        public System.Threading.Tasks.Task<string> insertPatientAsync(HospitalWebClient.HospitalService1.Patient patient) {
            return base.Channel.insertPatientAsync(patient);
        }
        
        public string updatePatient(HospitalWebClient.HospitalService1.Patient patient) {
            return base.Channel.updatePatient(patient);
        }
        
        public System.Threading.Tasks.Task<string> updatePatientAsync(HospitalWebClient.HospitalService1.Patient patient) {
            return base.Channel.updatePatientAsync(patient);
        }
        
        public void logout() {
            base.Channel.logout();
        }
        
        public System.Threading.Tasks.Task logoutAsync() {
            return base.Channel.logoutAsync();
        }
        
        public string bookAppointment(HospitalWebClient.HospitalService1.BookApp bapp) {
            return base.Channel.bookAppointment(bapp);
        }
        
        public System.Threading.Tasks.Task<string> bookAppointmentAsync(HospitalWebClient.HospitalService1.BookApp bapp) {
            return base.Channel.bookAppointmentAsync(bapp);
        }
    }
}
